### ISSUE TITLE
Where is the frontend?

### ISSUE THREAD

**Issue by pReya** [netcup-community/community-tutorials#103]
People have been adding to this repo for months now, but it seems that there is still no Frontend to render this content. Any updates on the status of this? Can the community help? Could this be a community effort?

**Comment by netcupChristophW** [comment]
Thank you very much for your interest. At this point in time, we are hard at work on creating the best design possible. As it stands right now, all I can say is that we intend to go live in the near future and we will of course inform the community as soon as that happens.

**Comment by netcupClaudiaM** [comment]
@pReya If you haven't seen it already on our social media channels or our forum, I'm happy to tell you there is a front end now: community.netcup.com
