### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by NyasakiAT** [netcup-community/community-tutorials#105]
community-tutorials/first-steps-to-protect-your-linux-server-against-common-attacks/01-en.md

Why are we enableing root login via ssh here?
And I'm kinda missing fail2ban

**Comment by netcupChristophW** [comment]
Hey,

netcup Tutorials are a community driven effort, with us mainly evaluating the technical accuracy and ensuring that every tutorial is easy to follow for the target user.

Fail2ban is explained in detail as part of a separate tutorial found here: https://github.com/netcup-community/community-tutorials/blob/main/community-tutorials/how-to-install-and-configure-fail2ban-on-debian/01-en.md The hardening tutorial you have mentioned also references and recommends this separate tutorial in the conculsion.

Concerning superuser via ssh, a previous reviewer made additions to improve readability, adding a "diff" at that point in the markdown file so users would more clearly notice the changes. They also modified the sentence explaining the change to make it more readable, but erroniously swapped the yes and no. I have adressed the issue. Thank you for bringing that mistake to our attention.

There is a debate to be had on whether PermitRootLogin no or without-password is ideal, though purely security wise, no is generally more advisable in most use cases.

Thank you for bringing this to our attention.
