### ISSUE TITLE
Multi-page tutorial

### ISSUE THREAD

**Issue by CuzImBisonratte** [netcup-community/community-tutorials#124]
Aktuell schreibe ich an einem Tutorial um auf einem eigenen Server PHPMyAdmin einzurichten.

Nachdem man das Haupttutorial beendet hat, funktioniert schon alles.
Ich würde aber gerne noch weitere, weiter in die Tiefe gehende, Tutorials, die aber auf dem Haupttutorial basieren schreiben.

Wie zum beispiel die Möglichkeit Themes zu installieren oder sonstige kosmetische anpassungen, sowie den PHPMyAdmin-Konfig.-Speicher zu aktivieren und sonstige.

Wie sollten diese geschrieben Sein?
- Möglichkeit 1: Alles in einem Tutorial mit Kapiteln - Wird halt sehr schnell unübersichtlich
- Möglichkeit 2: Alles in einzelnen Tutorials die in der Einleitung stehen haben, dass diese auf dem Haupttutorial aufbauen - Würde viele einzelne Tutorials mit sich bringen
- Möglichkeit 3: Alles in einem Tutorial Ordner, dann aber ineinander verlinkt - Falls dies Technisch möglich ist, stellt sich mir die Frage, wie dies geht

Ich hoffe es gibt dafür eine Lösung, die ich anwenden kann.

**Comment by CuzImBisonratte** [comment]
Referenz: #126

**Comment by netcupChristophW** [comment]
Hallo @CuzImBisonratte, vielen Dank für das eingereichte Tutorial. In diesem Fall wäre Option 2, also einzelne Tutorials, als einzlne Pull Requests eingereicht am Besten. Dadurch ist auch sichergestellt, dass die Coupons für das Verfassen der Tutorials schnellstmöglich bearbeitet werden. Ich werde Tutorial #126 direkt zur Review weitergeben. Vielen Dank für das Interesse und den Einsatz. Mit freundlichen Grüßen @netcupChristophW
