### ISSUE TITLE
Übersetzung fremder Tutorials

### ISSUE THREAD

**Issue by CuzImBisonratte** [netcup-community/community-tutorials#125]
Ist es erwünscht, fremde Tutorials zu übersetzen und wenn ja, wer sollte dann als Author in der Contribution stehen?

**Comment by netcupClaudiaM** [comment]
Dieses Feature ist bereits vorbereitet und wird beim nächsten Major Release von community.netcup.com umgesetzt werden. Danke für deine Idee! :) 
Lg, Claudia
