### ISSUE TITLE
Admonitions possible?

### ISSUE THREAD

**Issue by CuzImBisonratte** [netcup-community/community-tutorials#135]
Is it possible to anyhow include Admonitions in the markdown? 

One Implementation i really enjoy is the one Docusaurus uses: ![image](https://github.com/netcup-community/community-tutorials/assets/50182241/9de41d7c-ba68-493c-a5d8-1d3d4a2a0ce9)
![image](https://github.com/netcup-community/community-tutorials/assets/50182241/4d0915c4-547e-40d4-931b-3299fb7013de)

**Comment by netcupClaudiaM** [comment]
Hello @CuzImBisonratte, I just realized, we never gave you feedback on this one. This issue has found its way into our ticketing system, so we keep track of it. It should be possible to deploy this - it will be a question of time. Thank you for this great idea! :) 
Kind regards, 
Claudia H.
