### ISSUE TITLE
Informationen zu ehemals geschlossenen Issues

### ISSUE THREAD

**Issue by CuzImBisonratte** [netcup-community/community-tutorials#151]
Bezüglich #125 und #135, ich habe soeben die Commits 4170c41 und 9016651 entdeckt. Sind das sowohl admonitions als auch übersetzungen die jetzt ins system integriert sind?

Wenn ja, sind diese irgendwo dokumentiert bez. wie funktioniert die Gutscheinausgabe oder Namensnennung bei übersetzen Dokumenten und welche Admonition-Types sind verfügbar?

**Comment by netcupClaudiaM** [comment]
Hallo @CuzImBisonratte, 
für die Übersetzung von Tutorials gibt es keine Gutscheinausgabe. Die Namensnennung wird noch implementiert werden und aktuell steht der Admonition-Type "Info" zur Verfügung, der sich bereits im Template befindet.
