### ISSUE TITLE
Richtlinien für wichtigkeit der Tutorials

### ISSUE THREAD

**Issue by CuzImBisonratte** [netcup-community/community-tutorials#155]
Ich persönlich finde, dass Tutorials hier nicht einfach nur anleitungen sein sollten, welche zwei oder drei punkte umfassen, beispielsweise wie man einen vorgefertigten docker container zum laufen kriegt oder was man in einem Installationsskript angeben soll.

Wenn eine Software selber eine einfach auffindbare Dokumentation hat, welche die installation erklärt, sollten mMn. keine Tutorials zugelassen werden, welche keinen anderen Weg nutzen als die Dokumentation, da die Dokumentation oft natürlich besser up to date gehalten wird und die Dokumentation nur zu kopieren ja niemandem einen Mehrwert bringt.

Ich habe ja kein Problem damit, wenn man ein Tutorial macht, wie man Docker installiert, aber in Docker einen Container mit einem einzelnen oder zwei Befehlen zu starten ist, denke ich die genutzte Zeit zur überprüfung der Tutorials nicht wert..

Wäre es möglich, hierfür einfache Richtlinien zu entwickeln und diese in die README einzufügen?

**Comment by netcupClaudiaM** [comment]
Hallo @CuzImBisonratte, 
danke für deine Anregung. Wir finden, dass auch Anfänger etwas mit unseren Tutorials anfangen können sollen. Ob wir dabei bei der gegebenen Richtlinie bleiben oder nicht, werden wir zum gegebenen Zeitpunkt evaluieren.
